name: ZAP Security Scan

on:
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  zap_security_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up ZAP Work Directory
        run: mkdir -p ${{ github.workspace }}/zap/wrk

      - name: ZAP Security Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: ${{ github.event.before }}..${{ github.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'

      - name: Display ZAP Report
        run: cat ${{ github.workspace }}/zap/wrk/report_md.md

      - name: Display ZAP Error Log
        run: cat ${{ github.workspace }}/zap/wrk/error.log
